name: AllAPILoader
main: OhhhAlex\AllAPILoader\Main
version: 1.0.0
api: [3.0.0, 4.0.0]
author: TheNewHEROBRINE, JackMD, OhhhAlex
description: Makes the server load every plugin regardless of the API version
load: STARTUP
softdepend: ["DevTools", "FolderPluginLoader"]
